INSERT INTO PGJ.CALL_TYPE (NAME) VALUES ('Llamada Telefonica');
INSERT INTO PGJ.CALL_TYPE (NAME) VALUES ('RadioFrecuencia');
INSERT INTO PGJ.CALL_TYPE (NAME) VALUES ('Oficio');

INSERT INTO PGJ.JUDGE_GROUP (NAME, DESCRIPTION) VALUES ('Grupo 1','Grupo 1');
INSERT INTO PGJ.JUDGE_GROUP (NAME, DESCRIPTION) VALUES ('Grupo 2','Grupo 2');
INSERT INTO PGJ.JUDGE_GROUP (NAME, DESCRIPTION) VALUES ('Grupo 3','Grupo 3');
INSERT INTO PGJ.JUDGE_GROUP (NAME, DESCRIPTION) VALUES ('Grupo 4','Grupo 4');
INSERT INTO PGJ.JUDGE_GROUP (NAME, DESCRIPTION) VALUES ('GIDE','GIDE');
INSERT INTO PGJ.JUDGE_GROUP (NAME, DESCRIPTION) VALUES ('Guardias Viales','Guardias Viales');


INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (1, 'Benjamin Cortes Resendez');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (1, 'Daniela Guadalupe Hernandez Mendoza');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (1, 'Edith Paulina Moctezuma Malo');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (1, 'Edna Melissa Ramirez Rojas');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (1, 'Hector Gonzalez Valladares');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (1, 'Jorge A. Acosta Colchado');

INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (2, 'Cesar Augusto Gonzalez');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (2, 'Claudia Carmona Chavez');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (2, 'Cristina Martinez Pereyra');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (2, 'David L. Donjuan Acosta');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (2, 'Edgar Ivan Martinez');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (2, 'Jesus Tovar Lopez');

INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (3, 'Alma Judith Soto Villa');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (3, 'Cesar Falcon Guajardo');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (3, 'Gabriel Sotelo Ramos');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (3, 'Jose J. Torres Lopez');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (3, 'Carmen Sarahi Romo');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (3, 'Luis R. Lopez Lopez');

INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (4, 'Alma Cristina J. Villa');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (4, 'Cesar Falcon Guajardo');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (4, 'Gabriel Sotelo Ramos');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (4, 'Jose J. Torres Lopez');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (4, 'Carmen Sarahi Romo');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (4, 'Luis R. Lopez Lopez');

INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (5, 'Rafael Areola Vazquez');
INSERT INTO PGJ.JUDGE(JUDGE_GROUP_ID, NAME) VALUES (6, 'Silvino Castro Saucedo');

INSERT INTO PGJ.TOWN(NAME) VALUES ('Abasolo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Agualeguas');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Los Aldamas');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Allende');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Anáhuac');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Apodaca');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Aramberri');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Benito Juárez');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Bustamante');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Cadereyta Jiménez');
INSERT INTO PGJ.TOWN(NAME) VALUES ('El Carmen');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Cerralvo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Ciénega de Flores');
INSERT INTO PGJ.TOWN(NAME) VALUES ('China');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Doctor Arroyo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Doctor Coss');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Doctor González');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Galeana');
INSERT INTO PGJ.TOWN(NAME) VALUES ('García');
INSERT INTO PGJ.TOWN(NAME) VALUES ('General Bravo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('General Escobedo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('General Terán');
INSERT INTO PGJ.TOWN(NAME) VALUES ('General Treviño');
INSERT INTO PGJ.TOWN(NAME) VALUES ('General Zaragoza');
INSERT INTO PGJ.TOWN(NAME) VALUES ('General Zuazua');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Guadalupe');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Los Herreras');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Hidalgo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Higueras');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Hualahuises');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Iturbide');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Lampazos de Naranjo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Linares');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Marin');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Melchor Ocampo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Mier y Noriega');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Mina');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Montemorelos');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Monterrey');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Parás');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Pesquería');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Los Ramones');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Rayones');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Sabinas Hidalgo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Salinas Victoria');
INSERT INTO PGJ.TOWN(NAME) VALUES ('San Nicolás de los Garza');
INSERT INTO PGJ.TOWN(NAME) VALUES ('San Pedro Garza García');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Santa Catarina');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Santiago');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Vallecillo');
INSERT INTO PGJ.TOWN(NAME) VALUES ('Villaldama');


INSERT INTO PGJ.DEPENDENCE(NAME)
              VALUES ('No Aplica');

INSERT INTO PGJ.DEPENDENCE(NAME, STREET_AND_NO, SUBURB, TOWN_ID, POSTAL_CODE, BETWEEN_ST, LATITUDE, LONGITUDE, CUADRANT )
              VALUES ('Hospital Universitario', 'Av. Madero y Gonzalitos', 'Mitras Centro', 39, '64460', 'Madero y Gonzalitos', '25.689733','-100.349443','1');

COMMIT;